### ISSUE TITLE
[Upgrade] Unity 2018

### ISSUE THREAD

**Issue by BraedonWooding** [OrderOfThePorcupine/ProjectPorcupine#118]
> Note: Version is now 2018.3

Unity 2018.3 is now out of beta and is 'released', we could update to the newest version but I'm thinking we should stay on 5.6 for a little longer till more stability comes since currently every release seems to have compatibility breaking changes.  

Though I did want to gather opinion on this.  The features that are most useful to us is the tile map (the procedural one of course, though it still may not actually be useful enough for us to use), and mainly the layered 2D camera that make our current shader effort nicer and more of a native solution.  Which may actually improve performance by quite a bit (though I haven't done any benchmarking on the effect that the depth shaders have on the performance).  Furthermore the job system is VERY nice for some of the multi-threading stuff we will need, though I'm sure we will have to restructure stuff to utilise that to its maximum.

**Comment by dustinwloring1988** [comment]
I would like to wait until 2018.1 comes out since they have a new entity system and it really makes making multitheading easy.

**Comment by GamerGeeked** [comment]
It is still better not to have to go digging for a unity version.

**Comment by ritobanrc** [comment]
Can we get some information as to what would break if we updated?

**Comment by BraedonWooding** [comment]
My opinions on 2018: 
- Job System is barely implemented (missing NativeHashSet for example; well actually only has NativeSlice and NativeArray so is missing a ton but really the lack of HashSet/Map is gonna hurt us the most) but that is okay since we wouldn't look to use it for the first little while as we are changing structures or whatever
- TileMap while useful is probably not going to be used as the effort required to implement it is greater then just making ours more robust which it is quite robust already.
- Layered 2D camera is really just a performance gain since our layering is quite a short section of code and functionally works.

Overall: I think honestly that there isn't enough to pull us, however the fact that certain things are being deprecated in it such as support for certain systems and so on could be enough to make us transfer as otherwise we could end up building for architecture that we won't be able to support in the future.

**Comment by BraedonWooding** [comment]
I'm going to transfer to 2018 :).
