### ISSUE TITLE
[bug] NullPointer exception on anim.RunConditions.ParamConditions Visuals.cs line 85

### ISSUE THREAD

**Issue by RyTechro** [OrderOfThePorcupine/ProjectPorcupine#126]
### Expected behavior

Haven't narrowed down the issue, it seems that there is an object that has a anim but the RunConditions are null and this method assumes it always does. I am not familiar enough with the code to know if this is an issue with the method or that an anim should never have an empty running condition.

### Actual behavior

Spams the console with NullPointer exceptions. Haven't found the object or reproducible steps to get this issue. In trying to narrow down forgot to copy exception. Will add if it triggers again 

```
NullReferenceException: Object reference not set to an instance of an object
ProjectPorcupine.Buildable.Components.Visuals.FixedFrequencyUpdate (Single deltaTime) (at Assets/Scripts/Models/Buildable/Components/Visuals.cs:85)
Furniture.FixedFrequencyUpdate (Single deltaTime) (at Assets/Scripts/Models/Buildable/Furniture.cs:558)
TimeManager.ProcessUpdatables (Single deltaTime) (at Assets/Scripts/Models/Time/TimeManager.cs:240)
TimeManager.Update (Single time) (at Assets/Scripts/Models/Time/TimeManager.cs:203)
GameController.Update () (at Assets/Scripts/Controllers/GameController.cs:73)
```

**Comment by RyTechro** [comment]
Added stacktrace

**Comment by kd7uiy** [comment]
Do you have a trigger so it can be reproduced? Even if it isn't 100% of the time, it should help... Thanks for the trace!

**Comment by RyTechro** [comment]
Playing the game for a few minutes should trigger it

**Comment by kd7uiy** [comment]
I've added code in my test build that should inform of any kind of a log error, and I've also played for 10-20 minutes without seeing this. What buildings do you have constructed at the time?

**Comment by kd7uiy** [comment]
The problem absolutely is the Water Tank, as well as the Accumulator. Neither of them has a RunCondition, while both have UseAnimation. The question is, what do we do about them, and what do we do about items without a RunCondition at all with an animation.

I'm considering what to do about this now, but one of two things should happen.

1. Fix both Water_Tank and Accumulator, and post an error if this happens again.
2. If no RunConditions are included, assume it is always running.
