### ISSUE TITLE
When fuel depleates a nullpointer triggers

### ISSUE THREAD

**Issue by RyTechro** [OrderOfThePorcupine/ProjectPorcupine#135]
### Steps to reproduce
Found the issue with water_generator and fission_reactor

* Build water_generator
* Let it supply with ice
* Wait for waterlevel to reach 0.0% (Speed time up)
* Nullpointer starts spamming the console

### Expected behavior

Output is generated

### Actual behavior

Gives a nullpointer with \/ this trace

```
NullReferenceException: Object reference not set to an instance of an object
ProjectPorcupine.Buildable.Components.Workshop.CheckForInventoryAtOutput (ProjectPorcupine.Buildable.Components.ProductionChain prodChain) (at Assets/Scripts/Models/Buildable/Components/Workshop.cs:503)
ProjectPorcupine.Buildable.Components.Workshop.FixedFrequencyUpdate (Single deltaTime) (at Assets/Scripts/Models/Buildable/Components/Workshop.cs:274)
Furniture.FixedFrequencyUpdate (Single deltaTime) (at Assets/Scripts/Models/Buildable/Furniture.cs:558)
TimeManager.ProcessUpdatables (Single deltaTime) (at Assets/Scripts/Models/Time/TimeManager.cs:240)
TimeManager.Update (Single time) (at Assets/Scripts/Models/Time/TimeManager.cs:203)
GameController.Update () (at Assets/Scripts/Controllers/GameController.cs:73)
```

**Comment by RyTechro** [comment]
Further exploring the issue I found that it also triggers if a fission reactor or a water generator is depleted of fuel

**Comment by koosemose** [comment]
That's peculiar, this may be a regression, as it certainly worked in the past.

**Comment by RyTechro** [comment]
Updated title to represent the issue not the effects. Found that after this nullpointer all the jobs/entire game logic breaks
