### ISSUE TITLE
Better way to display failed unit tests

### ISSUE THREAD

**Issue by kd7uiy** [OrderOfThePorcupine/ProjectPorcupine#150]
Right now the unit tests that fail is shown, but is quite difficult to understand, and even harder to understand why it failed. It would be great if the failed unit tests in TravisCI was clearer, and the files overall were smaller, but more informative.

**Comment by koosemose** [comment]
There's nothing we can do about the files really, they're as unity makes them. The best we could do is parse what information is available and try to show it in as good a way as possible.

**Comment by kd7uiy** [comment]
I guess the unit test failing should be easy enough to duplicate in one's own machine, so it probably isn't an issue. Agree, and will close.

**Comment by koosemose** [comment]
There have been one or two cases where it hasn't been over the life of the project, where a unit test failure only happens on CI (but perhaps is rare enough that dealing with the awkward digging through the reports isn't *too* bad.
