### ISSUE TITLE
Clicking on the lower buttons twice should close the menu.

### ISSUE THREAD

**Issue by kd7uiy** [OrderOfThePorcupine/ProjectPorcupine#168]
I keep wanting to close the menus by clicking on the buttons again, or even clicking somewhere off of the dialog. Both should work, neither currently does.

**Comment by koosemose** [comment]
I could've sworn this used to work... at the very least I don't recall having the menus in the way all the time.

If I'm not just misremembering, then that might mean this is actually a bug, so you might want to see if there is any code that maybe *should* be doing this.

**Comment by onurtnrkl** [comment]
I'm trying to fix that. I analyze the code, it seems already has that feature but doesn't work. Problem is menuName never equals CurrentlyOpen, so Close statement not working while menu currently open.

**Comment by koosemose** [comment]
That suggests to me that the problem lies in the json file or the loading of the json file

**Comment by onurtnrkl** [comment]
Currently open is always null in debug. I serialized currently open field for watching what happens from the LeftMenu inspector. Currently open seems not always null in inspector, that seems works correctly. I'm so confused, I have never seen bug like that.

**Comment by onurtnrkl** [comment]
Fixed. But works for only left menu buttons. I pushed my commit, I will add for other bottom game buttons.

**Comment by BraedonWooding** [comment]
Close via #166

**Comment by BraedonWooding** [comment]
#166 did not fix this so reopening
