### ISSUE TITLE
Travis has deprecated Xcode 6.4

### ISSUE THREAD

**Issue by BraedonWooding** [OrderOfThePorcupine/ProjectPorcupine#176]
Is there a particular reason why we are on Xcode 6.4, can we upgrade freely?

Somewhat urgent as it says they will stop working January this year and it is February so really at any day they could just break.

**Comment by kd7uiy** [comment]
Didn't realize this was an issue. If you want to do the work to upgrade, go for it!

**Comment by BraedonWooding** [comment]
Closed via #182
