### ISSUE TITLE
Too many Localization Logs

### ISSUE THREAD

**Issue by BraedonWooding** [OrderOfThePorcupine/ProjectPorcupine#202]
i.e.

```
Loaded Localization at Path: /Users/ExampleUser/ProjectPorcupine/Assets/StreamingAssets/Localization/ur_PK.lang
// ... repeated for every localization
```

We really should have lesser logs (prefer to maybe have just one log that says loaded all localization's successfully - and maybe include all paths in that single log) rather than 80 or so.

**Comment by BraedonWooding** [comment]
Context: I had my debug channels setup wrong and so I also made a comment on there being a lot of job / path messages (and I thought that could be due to recent changes) but that was just me setting up debug channels wrong :).

This however I feel is still a valid issue.

**Comment by koosemose** [comment]
I disagree, being able to have extremely detailed logs when needed can be extremely useful, including stuff that is running right as it can help pinpoint exactly where something went wrong.

**Comment by NogginBops** [comment]
Do we still have the log channels? Because if we do then I think that this isn't really an issue

**Comment by koosemose** [comment]
We still have them, and this is the exact purpose they are for, so we can have extremely detailed verbose logs when needed. (I actually think we need more logs than we have presently, as most of the log statements were made when we still got the unity log spammed with everything and slowdowns because of them, so most were relatively conservative.)

**Comment by BraedonWooding** [comment]
Fair enough, it is mostly just my hate for clutter.  I'll close this then

**Comment by kd7uiy** [comment]
Maybe set the defaults to not as many logs?

**Comment by BraedonWooding** [comment]
I think that would be a bit hard to do (and we don't want it to be completely off for fresh installs) I think people will just do what I did originally which is turn off the channels that annoy them and aren't relevant to what they are doing atm.
