### ISSUE TITLE
UI on small resolutions could have some work done

### ISSUE THREAD

**Issue by BraedonWooding** [OrderOfThePorcupine/ProjectPorcupine#219]
Testing on a 1440x900 resolution, gets worse the smaller it gets for some things.

Most of the elements work well so I'm just going to make a list of stuff that doesn't work well;

- [ ] Context Menu

If you have any other cases of UI elements not scaling well please mention them felt we should have a thread of them :).

Examples of good/bad looking screen resolutions;

For example this is what settings menu looks like at a very small resolution;
![screen shot 2019-02-21 at 5 32 57 pm](https://user-images.githubusercontent.com/22880786/53148481-d7343900-35fe-11e9-95cc-0d625e668152.png)

What the context menu looks like (as well as how good everything else like the inventory spawner and the stuff on the right hand side scale);

![screen shot 2019-02-21 at 5 33 29 pm](https://user-images.githubusercontent.com/22880786/53148483-dac7c000-35fe-11e9-84ce-4a8eb14600b8.png)

What console looks like (note: some parts didn't scale well until recently);

![screen shot 2019-02-21 at 5 33 12 pm](https://user-images.githubusercontent.com/22880786/53148485-dd2a1a00-35fe-11e9-97d1-6a105e21a000.png)

**Comment by koosemose** [comment]
I *still* don't get why some things don't scale at all

**Comment by BraedonWooding** [comment]
I would classify things that don't scale as a bug as well (presuming they would thus go off the screen), what doesn't scale?

**Comment by koosemose** [comment]
I thought you were talking about things not scaling well... perhaps I misunderstood?

**Comment by BraedonWooding** [comment]
Nah you didn't, but for example in context menu they scale it just is that they don't scale enough (or scale wrongly) and that is quite common.  I guess I would personally call it underscaling (scaling too little) and overscaling (scaling too much) rather than not scaling at all but honestly in this case it is basically the same.

**Comment by koosemose** [comment]
Make sure you check it in a true screen resolution....

**Comment by BraedonWooding** [comment]
Yes I am; 1440x900 (is the lowest).  Shouldn't really matter however since scaling shouldn't be based of a screen resolution category.

**Comment by koosemose** [comment]
It's not, but if the ratios are outside of standard screen resolutions it's possible to not look as good as it should. If it's a 16:9 resolution everything *should* look good, a 4:3 will still look good but a bit crowded.

In actual functionality it's related to the screen height (this gives behavior identical or nearly identical to unity's natural scaling, which for some reason doesn't apply correctly to our ui). 

In theory 16:10 should work just fine (only with a smidgen more room between things horizontally), so it's *probably* not the ratio.

**Comment by BraedonWooding** [comment]
Yeh it definitely isn't the ratio in this case (the overlapping is definitely due to a lack of scaling or underscaling and blurry text is typically due to bad font size scaling)

**Comment by kd7uiy** [comment]
This is something I can probably tackle after I have finished the job manager upgrades.

**Comment by NogginBops** [comment]
UI text has always scaled really badly, so there is no surprise that it looks messed up here. It might be a problem of horizontal vs vertical scaling setting in the UI canvas. Unity might be scaling based on the vertical resolution instead of the horizontal one or vise versa. It might even be how the RectTransforms are setup so that the scaling doesn't work

**Comment by kd7uiy** [comment]
Unity actually accepted a bug report from me about how bad their UI text was. Their solution was to buy TextMeshPro. I have a high likelihood of implementing that across the board if I get started on it, but...
