### ISSUE TITLE
Construction of pipe and wire underneath walls

### ISSUE THREAD

**Issue by RyTechro** [OrderOfThePorcupine/ProjectPorcupine#226]
When placing a wire that runs underneath a wall it prevents it from constructing. I would expect that the wire should be able to be build from the wall next to it.

![schermafbeelding 2019-02-22 om 07 53 53](https://user-images.githubusercontent.com/8685947/53225094-2918a580-3677-11e9-8686-1046aabb95ab.png)

**Comment by kd7uiy** [comment]
I've added a fix to this in #222
