### ISSUE TITLE
Move Localization Repository into OrderOfThePorcupine

### ISSUE THREAD

**Issue by bjubes** [OrderOfThePorcupine/ProjectPorcupine#52]
Now that we have control of the organization where the project is located, it makes sense to move localization from https://github.com/QuiZr/ProjectPorcupineLocalization to a repo (or fork) under the control of OrderOfThePorcupine. 

Once the repo is created, I can submit a PR to use it instead.

**Comment by koosemose** [comment]
I thought I'd included you in my invites to the new team... my bad... though not absolutely sure if that allows you to create a new repo or not.

Is that the accurate repo? I thought at some point a fork was created off of it that we were using for some reason that I can't really recall.
