### ISSUE TITLE
Tiles still use BuildingJob

### ISSUE THREAD

**Issue by koosemose** [OrderOfThePorcupine/ProjectPorcupine#68]
Tiles still use BuildingJob which has been effectively replaced with OrderActions, this should likely be updated to use OrderActions (unless there is some technical reason that says otherwise), I'm not certain without examining the code if the existing Build OrderAction will work for tiles, so it may be possible a new OrderAction needs to be created (but it may not as well). If this is the last place BuildingJob is used, then we may wish to investigate removing BuildingJob (or whatever the attached class is named), unless there is somewhere not directly connected to the prototypes that it is used (and even then we should investigate upgrading to an appropriate OrderAction).

**Comment by BraedonWooding** [comment]
I'll have a gander and explore it a little more.

**Comment by koosemose** [comment]
Resolved
