### ISSUE TITLE
Need assistance in reviewing converted Data files (json from xml)

### ISSUE THREAD

**Issue by koosemose** [OrderOfThePorcupine/ProjectPorcupine#80]
For those not aware, I've recently been working on coding a tool to autoconvert our prototype data files from xml to json (rather than doing it by hand or using a generic xml to json tool so that the structure is consistent and can minimize cruft from the xml files that isn't needed for json). 

I believe I have completed the conversions, however, setting up the json reading will require changing structure in a few places (where things were structured to follow how the xml was laid out and that same structure makes things extremely awkward at best or impossible at worst for reading from json), and that may lead to destroying the converters ability to read xml (as it is easier to test reading from a dedicated tool than in PP).

Before I head down that road (that may be difficult to reverse, and extremely difficult to do without some potential destruction), I would like to ensure I've got the data files fully converted, without leaving any data out. To do that, I would like help, extra eyes on things to ensure that nothing is missed. So if others could look things over and compare the files to their xml equivalents, it would help me proceed to the next step much faster.

For the smaller files I only really need one extra set of eyes, but the larger ones (furniture in particular) multiple extra sets would ensure I don't lose data and add a lot more time to the process. So if folks could look over some, and post which ones they've reviewed (If any missing data is discovered, I only need to be aware of one instance of it, since it's automated if one is in error or missing, all will be in error or missing, and fixing it should fix it for all

Note: Any not marked that have already been reviewed, I either have not yet had an opportunity to update, or in the case of a complex file, deem it to require further review due to complexity (this primarily being furniture). 
Note 2: The comment of *Requires further Attention* is a note to myself that a file that has been looked at has some concerns that I need to address, and an updated version of it will be reuploaded for further review after concerns have been seen to. If you have reviewed something, and had concerns that I didn't account for in a reply and it hasn't been marked as *Requires further Attention* please let me know, I may overlook things from time to time.

- [x] [Headlines.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973240/Headlines.txt)
- [x] [Inventory.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973242/Inventory.txt)
- [x] [Need.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/978075/Need.txt) *Note: CompleteOnFail defaults to false, so isn't shown due to being default value*

- [x] [Overlay.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/978232/Overlay.txt)  *Min and Max will be removed from xml shortly*
- [x] [PerformanceHUDComponentGroups.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973243/PerformanceHUDComponentGroups.txt) 
- [x] [Quest.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973253/Quest.txt)
- [x] [RoomBehavior.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973244/RoomBehavior.txt)
- [x] [ScheduledEvents.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/989083/ScheduledEvents.txt)

- [x] [SettingsTemplate.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973254/SettingsTemplate.txt)
- [x] [Ships.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973247/Ships.txt) *Attempt conversion to using Vector2*
- [x] [Stats.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973246/Stats.txt)
- [x] [Tiles.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973248/Tiles.txt) *Empty Inventory shouldn't be included*
- [x] [Trader.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973252/Trader.txt)
- [x] [Utility.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973249/Utility.txt)
- [x] [ConsoleCommands.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973251/ConsoleCommands.txt)
- [x] [Currency.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973255/Currency.txt)
- [x] [Furniture.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973256/Furniture.txt) *Review Latest version*
- [x] [GameEvents.txt](https://github.com/OrderOfThePorcupine/ProjectPorcupine/files/973257/GameEvents.txt)

Note to self: Investigate empty template in comment at top of files.

Note to self: Review jsonDefaults for all values, keep eye out for nonvector2 coords, and either convert to vector2 or ensure defaults are defined in such a way as to have 0,0 default for the entire object, rather than 0 for x and y being defaults independently.

**Comment by Kjarrigan** [comment]
**Headlines.txt** - checked - nothing invalid found.

**Comment by Kjarrigan** [comment]
**Need.txt** - checked - Some stuff is missing:
* CompleteOnFail
* HighToLow
* Minor (the order seems somewhat random. would be nice if at least the RestoreNeed-Attributs would be together, for better readability but could be change by hand if needed.)

**Comment by koosemose** [comment]
Yes, thanks for the comments on order... the order of things that come from properties (such as the various RestoreNeeds* properties) is determined by the order those properties are in in the class, and the Properties I dummied out of the PP classes, so they're in whatever semirandom order they were added in. I'll look to put things in a more reasonable order, I already did that to a degree with the larger files that needed more managing, so feel free to point out any other files that have bad ordering, or any other situations where the formatting is somehow bad... of course "bad" is subjective so that can be hit or miss...

**Comment by BraedonWooding** [comment]
**GameEvent.txt** - checked - Good
- One thing though it has 'Preconditions' and 'ExecutionActions' which both contain function names to execute on either the precondition or on the actual execute.  So probably 'Preconditions' should be renamed to 'PreconditionActions' to keep consistency?

**Comment by BraedonWooding** [comment]
**Currency.txt** - perfect
- A bit explicit (object for each currency) but since at one point we will likely want to have more than just short name for each currency its future proof so its good.

**Comment by BraedonWooding** [comment]
**Furniture.txt** - all good
- Fits the XML perfectly and good use of encapsulation

**Comment by BraedonWooding** [comment]
**ConsoleCommands.txt** - Good
- I personally would like the tags on a single line since they are simple strings (just to reduce height) but that's a smile gripe so its good.

**Comment by Kjarrigan** [comment]
**Overlay.txt** - some stuff missing:
* _Min_ - for all elements
* _ColorMap_ - _missing_ for 5 of 8 elements - I guess you dropped them because its the default? With the missing comment telling me what the default is this might not be obvious for everyone.

How do we handle comments in general? JSON unfortunately doesn't allow them but the information should be somewhere and not just dropped. Maybe on a wiki page? Could be minimalistic. One page for all _data-tables_ with a short list of attribute-description pairs?

**Comment by Kjarrigan** [comment]
**PerformanceHUDComponentGroups.txt** - some stuff missing:
* _DisableUI_
* Its in the original data as well but why is _FPSPerformanceComponent_ listed twice in Extended and Verbose? Don't know if this could be used in other data elements as well but it might be cool to have some kind of inheritance among the elements. so you could write something like
inherits: ''Basic" and then just add the Elements which are new to this one.
And this really need some comments - false is no valid DisplayColor for me :smile:

**Comment by koosemose** [comment]
Was just about to add the checkmarks. 

And yes, it autodrops anything that is default, I can force it not to (such as I had to do with my dummy Vector2, as 0 is default for ints and floats, so it wouldn't show an X or Y of 0, which was a little strange.) As I'm converting the resulting objects, not the data itself, I can't preserve one entry showing defaults without all showing defaults, which would vastly balloon out the size of files (and impacting readability). 

And while JSON doesn't allow comments, Json.net does, so we can readd those afterwards (conversion of course won't preserve them). Once I get the json implemented, I will leave the xml data files in place long enough for us to transplant relevant comments.

I have no idea why FPSPerformanceComponent is listed twice, only that it's in the original xml, and I assume it is there for a reason.

Disable UI was intentionally removed as it no longer does anything and just wasn't removed (confirmed by @BraedonWooding the author of the related code and data files.

And I actually do intend on doing an inheritance system for prefabs in general, that I've been discussing in discord, but it will be waiting until I have the data functional in its basic form, I don't want to overcomplicate things by adding too much extra functionality.

**Comment by koosemose** [comment]
@BraedonWooding Regarding tags on ConsoleCommands, to the best of my knowledge my only options on formatting are either compact (absolutely everything on one line, not meant for human readability) or expanded (with everything on it's own line as it is now), if you can discover a way to tell json.net to do the json in a particular format (such as all tags on a single line), let me know. Otherwise, any formatting changes will have to be done manually (and the possible eventual editor will continue to use the fully expanded form, due to inability to do it without manually reformatting)

**Comment by BraedonWooding** [comment]
- @Kjarrigan, @koosemose it's added twice cause there are two cases it is used, for the current FPS (measured over a 0.5s period) and the average FPS counter (measured over a 5s period or however long), no point having two identical classes when you can obtain the same behaviour using custom parameters :D.
- DisableUI was removed due to me obtaining its original use another way :D.
- And yeah felt that was the case with the formatting being only two options (due to it being the same with XML) but felt I might as well mentioned it in case if there was any special behaviour.

**Comment by koosemose** [comment]
I *thought* that might be the case re: duplicated components, but wasn't absolutely certain, and therefore wasn't going to say one way or another.

**Comment by BraedonWooding** [comment]
Yep, just was confirming :D

**Comment by Kjarrigan** [comment]
**Quests.txt** - checked - nothing invalid found.

@koosemose dropping the defaults in most cases is fine I think in this particular case the comment clarifies the missing element. So I'm fine with the current state.

**Comment by Kjarrigan** [comment]
**RoomBehavior.txt** - checked some stuff missing:

* __Requirements__
* __Optional__ - might be due to the _empty_ element but would be better to make an empty array I think.

Another more general remark (the more files you look through the easier you find inconsistencies) - localization. That might be out of scope for this PR but should be targeted soon after merge. The later you start the worse it gets.... e.g. Quests is hardcoded in the data and Inventory has "too many" keys.  The projects I localize work with a yaml-styled language file (the lib is called i18n). So you dont have key-value pairs but a whole tree structure. So it would look something like:

```
en:
  Inventory:
    raw_iron:
      name: "Iron Ore"
      description: "Raw Iron Ore, it needs to be processed before it's useful."
  Quest:
    "Mining Drone Beta Test Program":
      Name: "Mining Drone Beta Test Program"
      Description: "Participate in the Beta Program of brand new mining Drones!"
```
No need to define some localization keys inside the data. My translation method then accepts an _path_ to the string like: `translate('Inventory.raw_iron.name')` or `translate('Inventory', element.get_name, 'name')` I don't know if there is something similiar in C# / Unity but it should?

**Comment by koosemose** [comment]
Localization is outside of the scope, the most I'll be doing related to Localization is sanitizing the key names (going with LocalizationDescription and LocalizationName). I wouldn't be opposed to a system that works like that, if it can be done in a performant way (having to parse a string like that with regularity might be bad, since a lot of this stuff is ran for UI updates, which means every frame). I would advise putting that forward in an issue of its own, but unless you think you can implement it, the chance of uptake is low, we have minimal developers at the time, and expect to continue that way until break time for schools, as that covers the bulk of our contributors.

And yes, Optional Requirements won't show if it's empty, which for general showing of the data, I think is a good thing. I'll look into if I can have a way to create a blank template commented out at the start of each file, with all things showing, but it might still require some additional filling in, if all else fails, we can add in examples when doing the pass of readding examples.

**Comment by koosemose** [comment]
Re: Overlay data

Min doesn't show due to "default" value of an int defaulting to 0. However, the fact that all overlays shown use the same min and max suggests to me that perhaps that doesn't need to be a configurable thing, and should instead just be "how the system works".

**Comment by BraedonWooding** [comment]
Yep I agree with that.

**Comment by koosemose** [comment]
Any other notable issues with any of these? I've looked over them repeatedly and they seem fine, but I've also been staring at them in some form or another for an extended time period, so my ability to visually spot issues is severely compromised.

**Comment by BraedonWooding** [comment]
I'll have a look through them, to be honest if there is at any point we can always revise.

**Comment by koosemose** [comment]
It's a matter of ensuring there's no data loss, that then would have to be fixed by someone going through and finding every instance of a missing property and readding it to the Json, as opposed to going through and *that* a property is missing. It's vastly less work to have a couple people skim through the data files to be fairly sure nothing is missing, than to have to dig through and find every specific instance of a thing missing.

Also, the more confident I am about the accuracy of the data, the more comfortable I am restructuring classes (particularly the autodeserialized ones).

**Comment by Kjarrigan** [comment]
**ScheduledEvents.txt** - seems fine. 

Some remarks - Now we have 3 lines with basically the same string: **ping_log_lua** as key, as Name and as LuaFunctionName, seems a bit redundant? Additionally there is now an EvenType which wasn't there before saying Lua. Any reasons for that? The FunctionName has alread Lua as prefix?

**Comment by Kjarrigan** [comment]
**SettingsTemplate.txt** - perfect.

**Comment by koosemose** [comment]
The name is redundant (it is literally just the same thing as the key), LuaFunctionName, while in this case is the same, that will not always be the case. EventType is redundant info as well, relating to the object structure (the object that stores it has to know it's a lua function, but by definition it being in data files means it has to be a lua function (or C#, but in this case they're called the same way and the script system figures out which one). I *thought* I had removed EventType and redundant Name, but either I didn't or I just forgot to upload the fixed version. Looking at it, it seems I just forgot to upload the fixed version, but for good measure I changed it to just "FunctionName" since it Lua is implied by being from data.

**Comment by Kjarrigan** [comment]
**Ships.txt** - the information is in there but.....
its ugly as hell with that many line for a "few" coordinates. The 0-values missing doesn't help either. They should be present to be honest. Two suggestions instead of two parameters (x,y) use one pos parameter containing x,y value. That would look better I think:

```
Storages: [
  { pos: "0,0" },
  { pos: "1,0" },
  { pos: "0,1" },
...
```

The second suggestion would be some kind of Matrix.

```
Layout: [
  [ "storage", "steel_wall", "storage" ],
  [ "storage", "floor"     , "storage" ],
  [ "floor"  , "floor"     , "floor  " ],
  [ "storage", "floor"     , "storage" ],
  [ "storage", "floor"     , "storage" ],
]

```

**Comment by Kjarrigan** [comment]
**Stats.txt** - perfect

**Comment by Kjarrigan** [comment]
**Tiles.txt** - needs some clarification:

- There is a _PathfindingWeight_ which is not in the xml
- _LinksToNeighbours_ missing (default?)
- _Inventory_ is there even if its empty but the JobTime of 0 is not

Other thant that its fine.

**Comment by Kjarrigan** [comment]
**Trader.txt** - fine.

For the records - need some explaining comments but I guess ideally we comment every of the txt files with the available Keys and Value Ranges and a Description. e.g. Rarity 0.8 means what? 80% chance to not get it?

**Comment by Kjarrigan** [comment]
**Utility.txt** - one remark:

- There is just one TypeTag in the xml but you made it an TypeTags-Array in the json?

After reviewing all this files I highly suggest to show the default values even if this might mean in some cases a quite large file but the reader has everything he needs to know. We can always remove really obvious defaults when we add the comments to the files.

**Comment by Kjarrigan** [comment]
**Furniture.txt** - that was quite a long one ... *ok* but some remarks:

- I would suggest to remove the value in _DefaultSpriteName_. I mean json is Key:Value Pairs and we have a sub-tree with a value-keyword? So something like this:
`"DefaultSpriteName": "steel_wall_"`
If you want to keep the sub-thingy for future extensions the key should be renamed to 
```
DefaultSprint: {
  Name: "steel_wall_"
}
```
- _UnlocalizedDescription_-missing
- some values here and there added which I guess are the default ones (e.g. DragType: Single, "InputHaulingJobsCount": "input_hauling_job_count", "HasAllNeededInputInventory": "has_all_needed_input_inv")
- on the other hand some other defaults are missing (e.g. MinLimit: 0, slotPosX: "0", slotPosY: "0", loops: true)
- JobOutputSpotOffset missing

**Comment by koosemose** [comment]
Yeah, furniture is the big one.

DefaultSpriteName's setup is due to how the xml and reading happen, I've been trying to fix up things that make for needless structure in the Json, but it can be tricky, I'll be sure to look into this one and see if I can change it at the conversion stage (if not, it will have to be done afterwards).

UnlocalizedDescription is changed to LocalizationDescription, for reasons of a little more sanity in the naming of the localization related values.

Regardomg defaults, I have to explicitly define what defaults are for non int and strings (ints default to 0, strings default to String.Empty)

I did some restructuring around JobOutputSpotOffset, so it may be renamed or live under a different structure, I'll look into it to ensure that it's present in some form or another.

TypeTags in Utility, while the two current examples only contain a single TypeTag, it is an array value in the code, and can contain multiples (as can the xml, in the same fashion as Furniture's Typetags, by having multiple <TypeTag> tags.

The various forms of things that have an X and Y with either X or Y missing is due to the object using something other than a vector2 to contain its coords, so it only looks at default int/float values of 0. I will need to look into converting them all into a reasonable usage of vector2, so that default is properly defined as 0,0, rather than having x and y separately have a default of 0.

re: Ships, I would rather avoid having a data structure that requires string parsing to get the underlying number values, that's more prone to user error in the formatting causing needless issues. And I would also prefer to avoid some kind of matrix set up, while it looks halfway decent, it ends up being more of an annoyance in actual editing (based on the fact that that form is similar to what was used to set up the starting base previously, and it was nothing but a headache, and no one touched it to update it prior to it being changed). I would rather do a complete overhaul of how ships are handled (assuming we even want to keep this type of ship, as we currently have two separate types of trading ships), something that can use a stripped down save file instead to read the ship from (allowing someone to use the game itself to create a ship), and then have ships.json simply refer to the save file used for the ship, and then any excess data for the ship.

Issues with Tiles is simply a problem with badly defined defaults (all current tiles in xml use the actual default, but I haven't properly defined the actual defaults are for json). With the empty inventory, it's another place where I need to tell it not to add an empty inventory.

All in all, aside from mentioned issues, I need to go through a pass on everything, see what defaults are treated as in code, and tell the Json what those defaults are.

**Comment by koosemose** [comment]
Thanks for all the help, I'll look to seeing to the default related issues, and see if I can't figure out a way to automatically add a commented version of an "empty" prototype for each, if not that will have to be added manually afterwards, along with readding any relevant comments.

**Comment by Kjarrigan** [comment]
Thanks for the clarifications. After all quite a solid base to work with so I'm confident that it should work without to much struggle. If you have made some changes and want another review for some of the files feel free to ask. Although I don't have much time to tackle issues needing long-sessions (and still have no actual unity-coding setup) I can spare a few minutes here and there to at least contribute by commenting or like in this case reviewing things.
