### ISSUE TITLE
No UI in latest Windows.Exe

### ISSUE THREAD

**Issue by DisturbedGoW** [OrderOfThePorcupine/ProjectPorcupine#87]
Hello everyone,

I have just recently downloaded the latest Windows version, I have restarted the game several times and changed to several Window sizes to see if the UI just outscaled.

I have tried pretty much everything I can think of, but I am not able to see the UI to do anything. The world spawns, the Characters seems to spawn correctly, but no Interface I can interact with.

![image](https://cloud.githubusercontent.com/assets/5146498/26081220/20bc13d2-39ca-11e7-8467-2accd5f8af15.png)

Kinds regards
Dist_TV

**Comment by koosemose** [comment]
I'm unable to recreate this, there's a possibility it has something to do with settings or perhaps localization that we don't get due to already having all the relevant files from development. I'll see if I can't recreate a starting setup, and failing that will see about looking at some logs. 

However, for the time being we are having issues with our automated build system, so the "latest" version is actually farther behind than it should be, we may have to get that resolved before we can properly look into this.

**Comment by Kjarrigan** [comment]
Hi @DisturbedGoW ,
we fixed the weekly builds so please download the true "latest" version of the game (2017.20) and check if it the problem is fixed.

**Comment by DisturbedGoW** [comment]
Hello there @Kjarrigan,

Will do as soon as I get home! :) 
Thanks for the quick responses!

**Comment by BraedonWooding** [comment]
Also just want to chime in and add, if it happens again could you tell us maybe a bit more about your machine?  Such as if you have a graphics card, OS version (just like windows 10 or 7 should be good enough, no need to go into real specifics), the size of your monitor is another huge one that is beneficial for testing.  Thanks again for creating this bug report :D.

**Comment by Kjarrigan** [comment]
@BraedonWooding I don't no much about Unity but could this be something we could built in the "game" - a Button in the Settings which collects all system information which are important for the debugging and and showing an popup or something similar where you can easily copy&paste the string to your github Ticket?

**Comment by BraedonWooding** [comment]
Yes, it would be easy to implement for future cases (though I guess if UI ain't working at all then you won't be able to find the button lol), I'll have a look into the 'best' place for it either as a key press or as a location in settings (I'm more leaning towards settings as you suggested).

**Comment by koosemose** [comment]
Hah, yes that would be useful in general, but probably wouldn't work so well in this case, lol... we/I should probably also look into adding something to the logging tool so that it can bypass the unity Console entirely, and perhaps just write things to file.

**Comment by koosemose** [comment]
Due to lack of response, Closing this, and assuming the errors were due to an older version in the binaries.

Should this not be the case, feel free to reopen with any further details of behavior.
