### ISSUE TITLE
Weeklies not uploading new versions

### ISSUE THREAD

**Issue by koosemose** [OrderOfThePorcupine/ProjectPorcupine#88]
We've got an issue with the weeklies, they can't be uploaded. The following error appears for each version in Travis: `Bintray response: 409 Conflict. Unable to upload files: An artifact with the path 'Windows.zip' already exists under another version`

So it seems, as best I can tell, all the files for each version live in the same directory, and without an option set for it, we can't overwrite it. I'm not absolutely sure if we would actually want to overwrite it, as that would mean we would only ever have the most recent version (and there could be benefit to having older versions archived. So barring setting `override=true` we need to either append the weekly version to the zip filename, or perhaps they need to be uploaded in such a way that each version exists in its own subdirectory (not entirely certain if this is an option with bintray).

Paging @Kjarrigan as you're more familiar with the system.

**Comment by Kjarrigan** [comment]
I'll look into this - but I already thought about that while writing the PR - thats why there is a version and at least with my few test runs it worked...

```
<% version = Time.now.strftime("%Y.%V") # (year).(week), e.g. 2017.15 %>
"version": {
        "name": "<%= version %>",
```
